### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by alexk1028** [cdr4eelz/serialhub#13]
pip install success
Jupyter-Lab version:3.0.15

Node version:12.22.5

cmd: jupyter labextension install @jupyter-widgets/jupyterlab-manager

error stack:

Node v12.22.5

Yarn configuration loaded.
> /usr/bin/npm pack @jupyter-widgets/jupyterlab-manager
npm notice 
npm notice 📦  @jupyter-widgets/jupyterlab-manager@3.0.1
npm notice === Tarball Contents === 
npm notice 14.5kB LICENSE             
npm notice 380B   lib/index.js        
npm notice 15.3kB lib/manager.js      
npm notice 5.3kB  lib/output.js       
npm notice 7.9kB  lib/plugin.js       
npm notice 3.3kB  lib/renderer.js     
npm notice 862B   lib/semvercache.js  
npm notice 3.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice 2.8kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 5.9kB  lib/manager.d.ts    
npm notice 1.9kB  lib/output.d.ts     
npm notice 828B   lib/plugin.d.ts     
npm notice 960B   lib/renderer.d.ts   
npm notice 216B   lib/semvercache.d.ts
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager         
npm notice version:       3.0.1                                       
npm notice filename:      jupyter-widgets-jupyterlab-manager-3.0.1.tgz
npm notice package size:  15.6 kB                                     
npm notice unpacked size: 64.0 kB                                     
npm notice shasum:        ba70c14282fb8bd3c6560588f4c7b90b2b2b05fb    
npm notice integrity:     sha512-yhmakhiAFtKtZ[...]RptG4BvNdS+HA==    
npm notice total files:   16                                          
npm notice 
jupyter-widgets-jupyterlab-manager-3.0.1.tgz

Fetching URL: https://registry.yarnpkg.com/@jupyter-widgets%2Fjupyterlab-manager
> /usr/bin/npm pack @jupyter-widgets/jupyterlab-manager@3.0.1
npm notice 
npm notice 📦  @jupyter-widgets/jupyterlab-manager@3.0.1
npm notice === Tarball Contents === 
npm notice 14.5kB LICENSE             
npm notice 380B   lib/index.js        
npm notice 15.3kB lib/manager.js      
npm notice 5.3kB  lib/output.js       
npm notice 7.9kB  lib/plugin.js       
npm notice 3.3kB  lib/renderer.js     
npm notice 862B   lib/semvercache.js  
npm notice 3.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice 2.8kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 5.9kB  lib/manager.d.ts    
npm notice 1.9kB  lib/output.d.ts     
npm notice 828B   lib/plugin.d.ts     
npm notice 960B   lib/renderer.d.ts   
npm notice 216B   lib/semvercache.d.ts
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager         
npm notice version:       3.0.1                                       
npm notice filename:      jupyter-widgets-jupyterlab-manager-3.0.1.tgz
npm notice package size:  15.6 kB                                     
npm notice unpacked size: 64.0 kB                                     
npm notice shasum:        ba70c14282fb8bd3c6560588f4c7b90b2b2b05fb    
npm notice integrity:     sha512-yhmakhiAFtKtZ[...]RptG4BvNdS+HA==    
npm notice total files:   16                                          
npm notice 
jupyter-widgets-jupyterlab-manager-3.0.1.tgz

Node v12.22.5

Yarn configuration loaded.
> /usr/bin/npm pack serialhub
npm notice 
npm notice 📦  serialhub@0.0.6
npm notice === Tarball Contents === 
npm notice 0      package             
npm notice 1.5kB  LICENSE.txt         
npm notice 626B   README.md           
npm notice 0      css                 
npm notice 0      dist                
npm notice 0      lib                 
npm notice 2.8kB  package.json        
npm notice 311B   css/widget.css      
npm notice 15.4kB dist/index.js       
npm notice 748B   lib/extension.js    
npm notice 394B   lib/index.js        
npm notice 1.5kB  lib/plugin.js       
npm notice 528B   lib/version.js      
npm notice 4.6kB  lib/webseriallink.js
npm notice 4.3kB  lib/widget.js       
npm notice === Tarball Details === 
npm notice name:          serialhub                               
npm notice version:       0.0.6                                   
npm notice filename:      serialhub-0.0.6.tgz                     
npm notice package size:  10.5 kB                                 
npm notice unpacked size: 32.7 kB                                 
npm notice shasum:        75a9d3f654815ee6250a87780a38fe50c1cbbd1b
npm notice integrity:     sha512-y1JaToC6qHKfW[...]98wnVhnFetNWg==
npm notice total files:   15                                      
npm notice 
serialhub-0.0.6.tgz

Node v12.22.5

Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node /usr/local/lib/python3.6/dist-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
error Package "" refers to a non-existing file '"/usr/local/share/jupyter/packages/translation-extension"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

npm dependencies failed to install
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/usr/local/lib/python3.6/dist-packages/jupyterlab/labextensions.py", line 134, in start
    production = production, minimize = self.minimize, app_options=app_options)

  File "/usr/local/lib/python3.6/dist-packages/jupyterlab/commands.py", line 470, in build
    production=production, minimize=minimize, clean_staging=clean_staging)

  File "/usr/local/lib/python3.6/dist-packages/jupyterlab/commands.py", line 669, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

Exiting application: lab

**Comment by cdr4eelz** [comment]
Thank you alexk1028 for trying out the installation.  I am not expert enough to know exactly what went wrong with the install, but if you have a chance please try again with a new version.  I have revived work on the project and updated many things (including using a new version of the "cookiecutter" template for TypeScript Widgets) that hopefully help.

I am not certain that the jupyter-labmanager is required, that step is part of the cookiecutter template, though.  Please try a "pip install serialhub", followed by "jupyter labextension list" to see if serialhub shows up as expected and is marked as "OK" status???

If it shows up, then refresh the browser (to let the newly installed javascript portion load) and use the steps like in the first couple cells of the examples/firsttest.ipynb notebook!  Let me know how it goes ;).  Thanks again for testing things at such an early stage!

**Comment by cdr4eelz** [comment]
Note that besides new packaging tests and whatnot...there is a link to open the extension in "binder" which will have it pre-installed (and serves as a test of the install success as well).

**Comment by cdr4eelz** [comment]
I believe that the install issue is resolved and that jupyterlab-manager itself is optional anyway.  The serialhub package itself should install cleanly with "pip install serialhub" and the project now has github actions to validate the install and basic use of the extension.

Marking resolved unless further details come up...
